layout: app
title: Tales Beneath the Surface
base_url: https://talesbeneaththesurface.com
podcast_category: Fiction
podcast_language: en-gb
podcast_subtitle: A horror anthology podcast
podcast_author: Tales Beneath the Surface
podcast_summary: <![CDATA[Welcome, dear listener, to Tales Beneath the Surface, a serialised journey into the unknown born in the dark heart of London.<br/><br/>Follow the mysterious Narrator through tales of woe and wonder where perception falters and the familiar becomes strange.<br/><br/>Each episode is scored with original music to draw you deeper into the dark and unearth fragments of the world beneath, things best left forgotten.<br/><br/>Join us and remember....reality writes itself.]]>
podcast_explicit: 'yes'
podcast_email: info@talesbeneaththesurface.com
podcast_img_url: https://tales-beneath-the-surface-files.b-cdn.net/Tales-3000-min.jpg
